def get_sales_order_fields():
	return [
		{
			"fieldname": "transport_dispatch_section",
			"fieldtype": "Section Break",
			"label": "Transport Dispatch",
			"collapsible": 1,
			"insert_after": "items",
		},
		{
			"fieldname": "require_direct_delivery",
			"fieldtype": "Check",
			"label": "Require Direct Delivery",
			"insert_after": "transport_dispatch_section",
		},
		{
			"fieldname": "transport_customer",
			"fieldtype": "Link",
			"label": "Transport Customer",
			"options": "Transport Customer",
			"insert_after": "require_direct_delivery",
		},
		{
			"fieldname": "transport_customer_name",
			"fieldtype": "Data",
			"label": "Transport Customer Name",
			"insert_after": "transport_customer",
		},
		{
			"fieldname": "transport_phone",
			"fieldtype": "Data",
			"label": "Transport Phone",
			"insert_after": "transport_customer_name",
		},
		{
			"fieldname": "transport_email",
			"fieldtype": "Data",
			"label": "Transport Email",
			"insert_after": "transport_phone",
		},
		{
			"fieldname": "transport_address",
			"fieldtype": "Text",
			"label": "Transport Address",
			"insert_after": "transport_email",
		},
		{
			"fieldname": "transport_column_break",
			"fieldtype": "Column Break",
			"insert_after": "transport_address",
		},
		{
			"fieldname": "driver",
			"fieldtype": "Link",
			"label": "Driver",
			"options": "Driver",
			"insert_after": "transport_column_break",
		},
		{
			"fieldname": "expected_delivery_date",
			"fieldtype": "Date",
			"label": "Expected Delivery Date",
			"insert_after": "driver",
		},
		{
			"fieldname": "transport_charge",
			"fieldtype": "Currency",
			"label": "Transport Charge",
			"insert_after": "expected_delivery_date",
		},
		{
			"fieldname": "custom_main_company_invoice",
			"fieldtype": "Link",
			"options": "Sales Invoice",
			"label": "Main Company Invoice",
			"insert_after": "transport_charge",
			"read_only": 1,
		},
		{
			"fieldname": "custom_main_company_invoice_date",
			"fieldtype": "Date",
			"label": "Main Company Invoice Date",
			"insert_after": "custom_main_company_invoice",
			"fetch_from": "custom_main_company_invoice.posting_date",
			"read_only": 1,
		},
		{
			"fieldname": "custom_last_customer_invoice",
			"fieldtype": "Data",
			"label": "Transport Customer Invoice",
			"insert_after": "custom_main_company_invoice_date",
		},
		{
			"fieldname": "custom_last_customer_invoice_date",
			"fieldtype": "Date",
			"label": "Transport Customer Invoice Date",
			"insert_after": "custom_last_customer_invoice",
		},
		{
			"fieldname": "custom_last_customer_delivery_note",
			"fieldtype": "Data",
			"label": "Transport Customer Delivery Note",
			"insert_after": "custom_last_customer_invoice_date",
		},
		{
			"fieldname": "custom_last_customer_delivery_note_date",
			"fieldtype": "Date",
			"label": "Transport Customer Delivery Note Date",
			"insert_after": "custom_last_customer_delivery_note",
		},
		{
			"fieldname": "custom_final_customer_feedback_document",
			"fieldtype": "Attach",
			"label": "Transport Customer Feedback Document",
			"insert_after": "custom_last_customer_delivery_note_date",
			"allow_on_submit": 1,
		},
		{
			"fieldname": "custom_note",
			"fieldtype": "Small Text",
			"label": "Note",
			"insert_after": "custom_final_customer_feedback_document",
			"allow_on_submit": 1,
		},
		{
			"fieldname": "custom_reschedule_transport_order",
			"fieldtype": "Check",
			"label": "Reschedule Transport Order",
			"insert_after": "custom_note",
		},
		{
			"fieldname": "custom_reason_for_reschedule",
			"fieldtype": "Small Text",
			"label": "Reason for Reschedule",
			"insert_after": "custom_reschedule_transport_order",
			"depends_on": "eval:doc.custom_reschedule_transport_order",
		},
		{
			"fieldname": "transport_charge_order_section",
			"fieldtype": "Section Break",
			"label": "Transport Charge Order",
			"collapsible": 1,
			"insert_after": "custom_reason_for_reschedule",
		},
		{
			"fieldname": "custom_is_transport_order",
			"fieldtype": "Check",
			"label": "Is Transport Order",
			"read_only": 1,
			"insert_after": "transport_charge_order_section",
		},
		{
			"fieldname": "custom_delivery_note_to_be_transported",
			"fieldtype": "Link",
			"label": "Delivery Note To Be Transported",
			"options": "Delivery Note",
			"read_only": 1,
			"insert_after": "custom_is_transport_order",
		},
		{
			"fieldname": "custom_address_zone",
			"fieldtype": "Link",
			"label": "Address Zone",
			"options": "Address Zone",
			"insert_after": "custom_delivery_note_to_be_transported",
		},
		{
			"fieldname": "custom_completed_without_otp",
			"fieldtype": "Check",
			"label": "Completed Without OTP",
			"read_only": 1,
			"allow_on_submit": 1,
			"insert_after": "custom_address_zone",
		},
	]


def get_delivery_note_fields():
	return [
		{
			"fieldname": "transport_dispatch_section",
			"fieldtype": "Section Break",
			"label": "Transport Dispatch",
			"collapsible": 1,
			"insert_after": "items",
		},
		{
			"fieldname": "require_direct_delivery",
			"fieldtype": "Check",
			"label": "Require Direct Delivery",
			"read_only": 1,
			"insert_after": "transport_dispatch_section",
		},
		{
			"fieldname": "transport_customer",
			"fieldtype": "Link",
			"label": "Transport Customer",
			"options": "Transport Customer",
			"read_only": 1,
			"insert_after": "require_direct_delivery",
		},
		{
			"fieldname": "transport_customer_name",
			"fieldtype": "Data",
			"label": "Transport Customer Name",
			"read_only": 1,
			"insert_after": "transport_customer",
		},
		{
			"fieldname": "transport_phone",
			"fieldtype": "Data",
			"label": "Transport Phone",
			"read_only": 1,
			"insert_after": "transport_customer_name",
		},
		{
			"fieldname": "transport_email",
			"fieldtype": "Data",
			"label": "Transport Email",
			"read_only": 1,
			"insert_after": "transport_phone",
		},
		{
			"fieldname": "transport_address",
			"fieldtype": "Text",
			"label": "Transport Address",
			"read_only": 1,
			"insert_after": "transport_email",
		},
		{
			"fieldname": "transport_status_column",
			"fieldtype": "Column Break",
			"insert_after": "transport_address",
		},
		{
			"fieldname": "delivery_status",
			"fieldtype": "Select",
			"label": "Delivery Status",
			"options": "\nOpen\nIn Transit\nPending Invoicing\nCompleted",
			"default": "Open",
			"read_only": 1,
			"in_list_view": 1,
			"in_standard_filter": 1,
			"insert_after": "transport_status_column",
		},
		{
			"fieldname": "otp",
			"fieldtype": "Data",
			"label": "OTP",
			"read_only": 1,
			"insert_after": "delivery_status",
		},
		{
			"fieldname": "otp_generated_at",
			"fieldtype": "Datetime",
			"label": "OTP Generated At",
			"read_only": 1,
			"insert_after": "otp",
		},
		{
			"fieldname": "otp_expires_at",
			"fieldtype": "Datetime",
			"label": "OTP Expires At",
			"read_only": 1,
			"insert_after": "otp_generated_at",
		},
		{
			"fieldname": "confirmation_log",
			"fieldtype": "Link",
			"label": "Confirmation Log",
			"options": "Delivery Confirmation Log",
			"read_only": 1,
			"insert_after": "otp_expires_at",
		},
		{
			"fieldname": "sms_status",
			"fieldtype": "Select",
			"label": "SMS Status",
			"options": "\nNot Sent\nPartially Sent\nSent\nFailed",
			"default": "Not Sent",
			"read_only": 1,
			"in_list_view": 1,
			"insert_after": "confirmation_log",
		},
		{
			"fieldname": "email_status",
			"fieldtype": "Select",
			"label": "Email Status",
			"options": "\nNot Sent\nPartially Sent\nSent\nFailed",
			"default": "Not Sent",
			"read_only": 1,
			"in_list_view": 1,
			"insert_after": "sms_status",
		},
		{
			"fieldname": "transport_sales_order",
			"fieldtype": "Link",
			"label": "Transport Sales Order",
			"options": "Sales Order",
			"read_only": 1,
			"insert_after": "email_status",
		},
		{
			"fieldname": "transport_sales_invoice",
			"fieldtype": "Link",
			"label": "Transport Sales Invoice",
			"options": "Sales Invoice",
			"read_only": 1,
			"insert_after": "transport_sales_order",
		},
	]


def get_driver_fields():
	return [
		{
			"fieldname": "transport_dispatch_section",
			"fieldtype": "Section Break",
			"label": "Ultra Dispatch",
			"collapsible": 1,
			"insert_after": "cell_number",
		},
		{
			"fieldname": "unique_key",
			"fieldtype": "Data",
			"label": "PIN",
			"unique": 1,
			"read_only": 1,
			"insert_after": "transport_dispatch_section",
		},
		{
			"fieldname": "vehicle_number",
			"fieldtype": "Data",
			"label": "Vehicle Number",
			"insert_after": "unique_key",
		},
		{
			"fieldname": "transport_company",
			"fieldtype": "Link",
			"label": "Transport Company",
			"options": "Company",
			"insert_after": "vehicle_number",
		},
	]


def get_custom_fields():
	return {
		"Sales Order": get_sales_order_fields(),
		"Delivery Note": get_delivery_note_fields(),
		"Driver": get_driver_fields(),
	}

